version: "3.8"

services:
  app:
    container_name: app-prod
    image: app-prod
    build:
      context: ../
      dockerfile: ./docker/prod.Dockerfile
      target: production
    ports:
      - 80:80