name: "Build Docker image"

on:
  push:
    tags:
      - 'release-*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo IMAGE_NAME=$(echo "${{ github.repository }}:${GITHUB_REF/refs\/tags\/release\-/}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          push: true